import { MaterialIcons } from '@expo/vector-icons';
import { Image, Pressable, Text, View } from 'react-native';
import { IssueListItem, IssueStatus, Priority, ProjectIssue, UserSummary } from '@/src/types';

type IssueCardIssue = IssueListItem | ProjectIssue;
const statusStyle: Record<IssueStatus, { background: string; text: string }> = { OPEN: { background: 'bg-emerald-100', text: 'text-emerald-700' }, IN_REVIEW: { background: 'bg-blue-100', text: 'text-blue-700' }, CLOSED: { background: 'bg-slate-200', text: 'text-slate-600' } };
const priorityStyle: Record<Priority, { dot: string; text: string }> = { CRITICAL: { dot: 'bg-red-500', text: 'text-red-700' }, HIGH: { dot: 'bg-orange-500', text: 'text-orange-700' }, MEDIUM: { dot: 'bg-amber-400', text: 'text-amber-700' }, LOW: { dot: 'bg-slate-400', text: 'text-slate-600' } };

export function StatusBadge({ status }: { status: IssueStatus }) { const style = statusStyle[status]; return <View className={`rounded-md px-2 py-1 ${style.background} dark:bg-opacity-70`}><Text className={`text-[10px] font-bold tracking-wide ${style.text}`}>{status.replace('_', ' ')}</Text></View>; }
export function PriorityBadge({ priority }: { priority: Priority }) { const style = priorityStyle[priority]; return <View className="flex-row items-center gap-1"><View className={`h-2 w-2 rounded-full ${style.dot}`} /><Text className={`text-[11px] font-semibold ${style.text}`}>{priority}</Text></View>; }
export function Avatar({ user, size = 'small' }: { user: UserSummary | null; size?: 'small' | 'medium' }) { const dimensions = size === 'medium' ? 'h-10 w-10' : 'h-6 w-6'; if (!user) return <View className={`${dimensions} items-center justify-center rounded-full bg-slate-100 dark:bg-slate-700`}><MaterialIcons name="person-outline" size={size === 'medium' ? 20 : 14} color="#94a3b8" /></View>; if (user.avatarUrl) return <Image source={{ uri: user.avatarUrl }} className={`${dimensions} rounded-full bg-slate-200 dark:bg-slate-700`} />; return <View className={`${dimensions} items-center justify-center rounded-full bg-indigo-100 dark:bg-indigo-950`}><Text className={size === 'medium' ? 'text-sm font-bold text-indigo-700 dark:text-indigo-300' : 'text-[10px] font-bold text-indigo-700 dark:text-indigo-300'}>{user.name.charAt(0).toUpperCase()}</Text></View>; }
export function IssueCard({ issue, onPress, showSwipeHint = false }: { issue: IssueCardIssue; onPress: () => void; showSwipeHint?: boolean }) { const comments = '_count' in issue ? issue._count.comments : 0; return <Pressable onPress={onPress} className="mb-2 rounded-xl border border-border bg-surface px-4 py-3 shadow-sm dark:border-border-dark dark:bg-surface-dark"><Text className="text-base font-semibold text-foreground dark:text-foreground-dark" numberOfLines={1}>{issue.title}</Text><View className="mt-2 flex-row items-center gap-2"><StatusBadge status={issue.status} /><PriorityBadge priority={issue.priority} /><Avatar user={issue.assignee} /><View className="ml-auto flex-row items-center gap-1"><MaterialIcons name="chat-bubble-outline" size={15} color="#94a3b8" /><Text className="text-xs text-muted dark:text-muted-dark">{comments}</Text>{showSwipeHint && <MaterialIcons name="chevron-left" size={17} color="#94a3b8" />}</View></View></Pressable>; }
