import { FontAwesome, MaterialIcons } from '@expo/vector-icons';
import { useState } from 'react';
import { ActivityIndicator, Alert, Image, Linking, Modal, Pressable, ScrollView, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useUpdateProfile } from '@/src/api/hooks';
import { ThemeMode, useThemeStore } from '@/src/store/useThemeStore';
import { User } from '@/src/types';
import { getErrorMessage } from '@/src/utils/error';

const fieldClass = 'rounded-xl border border-border bg-slate-50 px-4 py-3 text-foreground dark:border-border-dark dark:bg-slate-800 dark:text-foreground-dark';

export function ProfileRedesign({ user, onLogout }: { user: User; onLogout: () => Promise<void> }) {
  const updateProfile = useUpdateProfile(); const themeMode = useThemeStore((state) => state.themeMode); const setThemeMode = useThemeStore((state) => state.setThemeMode);
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({ jobTitle: user.jobTitle || '', bio: user.bio || '', skills: user.skills.join(', '), githubUrl: user.githubUrl || '', linkedinUrl: user.linkedinUrl || '', yearsExperience: user.yearsExperience?.toString() || '', location: user.location || '' });
  const openEditor = () => { setForm({ jobTitle: user.jobTitle || '', bio: user.bio || '', skills: user.skills.join(', '), githubUrl: user.githubUrl || '', linkedinUrl: user.linkedinUrl || '', yearsExperience: user.yearsExperience?.toString() || '', location: user.location || '' }); setEditing(true); };
  const save = async () => { try { await updateProfile.mutateAsync({ jobTitle: form.jobTitle.trim() || undefined, bio: form.bio.trim() || undefined, skills: form.skills.split(',').map((skill) => skill.trim()).filter(Boolean), githubUrl: form.githubUrl.trim() || undefined, linkedinUrl: form.linkedinUrl.trim() || undefined, yearsExperience: form.yearsExperience ? Number(form.yearsExperience) : undefined, location: form.location.trim() || undefined }); setEditing(false); } catch (error) { Alert.alert('Error', getErrorMessage(error)); } };
  const link = (url: string | null) => url && Linking.openURL(url).catch(() => Alert.alert('Error', 'Could not open this link'));
  const host = (url: string) => url.replace(/^https?:\/\/(www\.)?/, '').replace(/\/$/, '');
  const set = (key: keyof typeof form) => (value: string) => setForm((current) => ({ ...current, [key]: value }));
  const field = (label: string, key: keyof typeof form, placeholder: string, options?: { multiline?: boolean; keyboardType?: 'numeric' | 'url' }) => <View className="mb-4"><Text className="mb-2 text-xs font-bold uppercase tracking-wide text-muted dark:text-muted-dark">{label}</Text><TextInput className={fieldClass} placeholder={placeholder} placeholderTextColor="#94a3b8" value={form[key]} onChangeText={set(key)} multiline={options?.multiline} keyboardType={options?.keyboardType} autoCapitalize={options?.keyboardType === 'url' ? 'none' : 'sentences'} textAlignVertical={options?.multiline ? 'top' : 'center'} /></View>;
  return <SafeAreaView className="flex-1 bg-background dark:bg-background-dark"><ScrollView className="flex-1" contentContainerStyle={{ paddingHorizontal: 20, paddingBottom: 36 }}><View className="items-center pb-8 pt-7"><View className="h-28 w-28 items-center justify-center overflow-hidden rounded-full border-4 border-surface bg-indigo-100 shadow-sm dark:border-surface-dark dark:bg-indigo-950">{user.avatarUrl ? <Image source={{ uri: user.avatarUrl }} className="h-full w-full" /> : <Text className="text-4xl font-bold text-indigo-700 dark:text-indigo-300">{user.name.split(' ').map((name) => name[0]).slice(0, 2).join('').toUpperCase()}</Text>}</View><Text numberOfLines={2} className="mt-4 text-center text-2xl font-bold text-foreground dark:text-foreground-dark">{user.name}</Text><Text numberOfLines={2} className="mt-1 text-center text-base font-semibold text-blue-600 dark:text-blue-400">{user.jobTitle}</Text><Text numberOfLines={1} className="mt-1 text-center text-sm text-muted dark:text-muted-dark">{user.email}</Text><TouchableOpacity onPress={openEditor} activeOpacity={0.75} className="mt-5 flex-row items-center rounded-xl border border-border bg-surface px-4 py-2.5 dark:border-border-dark dark:bg-surface-dark"><MaterialIcons name="edit" size={17} color="#60a5fa" /><Text className="ml-2 font-semibold text-foreground dark:text-foreground-dark">Edit Profile</Text></TouchableOpacity></View>
    {user.bio && <View className="mb-7"><Text className="mb-2 text-xs font-bold uppercase tracking-widest text-muted dark:text-muted-dark">About</Text><Text className="text-[15px] leading-6 text-slate-700 dark:text-slate-200">{user.bio}</Text></View>}
    <View className="mb-7"><View className="mb-3 flex-row items-center justify-between"><Text className="text-xs font-bold uppercase tracking-widest text-muted dark:text-muted-dark">Skills</Text>{!user.skills.length && <TouchableOpacity onPress={openEditor}><Text className="text-sm font-semibold text-blue-600 dark:text-blue-400">Add your skills</Text></TouchableOpacity>}</View>{user.skills.length > 0 && <View className="flex-row flex-wrap gap-2">{user.skills.map((skill) => <View key={skill} className="rounded-full bg-blue-50 px-3 py-1.5 dark:bg-blue-950"><Text className="text-sm font-medium text-blue-700 dark:text-blue-300">{skill}</Text></View>)}</View>}</View>
    {(user.location || user.yearsExperience != null) && <View className="mb-7 rounded-2xl border border-border bg-surface p-4 dark:border-border-dark dark:bg-surface-dark"><Text className="mb-3 text-xs font-bold uppercase tracking-widest text-muted dark:text-muted-dark">Professional</Text>{user.yearsExperience != null && <View className="flex-row items-center"><View className="mr-3 h-9 w-9 items-center justify-center rounded-lg bg-blue-50 dark:bg-blue-950"><MaterialIcons name="work-outline" size={19} color="#60a5fa" /></View><View><Text className="text-sm text-muted dark:text-muted-dark">Experience</Text><Text className="font-semibold text-foreground dark:text-foreground-dark">{user.yearsExperience}+ {user.yearsExperience === 1 ? 'year' : 'years'}</Text></View></View>}{user.location && <View className={`flex-row items-center ${user.yearsExperience != null ? 'mt-4 border-t border-border pt-4 dark:border-border-dark' : ''}`}><MaterialIcons name="location-on" size={20} color="#94a3b8" /><Text className="ml-2 text-sm text-muted dark:text-muted-dark" numberOfLines={1}>{user.location}</Text></View>}</View>}
    {(user.githubUrl || user.linkedinUrl) && <View className="mb-7"><Text className="mb-3 text-xs font-bold uppercase tracking-widest text-muted dark:text-muted-dark">Connect</Text><View className="overflow-hidden rounded-2xl border border-border bg-surface dark:border-border-dark dark:bg-surface-dark">{user.githubUrl && <TouchableOpacity onPress={() => link(user.githubUrl)} activeOpacity={0.7} className="flex-row items-center px-4 py-3.5"><FontAwesome name="github" size={22} color="#94a3b8" /><View className="ml-3 flex-1"><Text className="font-semibold text-foreground dark:text-foreground-dark">GitHub</Text><Text className="mt-0.5 text-xs text-muted dark:text-muted-dark" numberOfLines={1}>{host(user.githubUrl)}</Text></View><MaterialIcons name="open-in-new" size={18} color="#94a3b8" /></TouchableOpacity>}{user.githubUrl && user.linkedinUrl && <View className="ml-12 border-t border-border dark:border-border-dark" />}{user.linkedinUrl && <TouchableOpacity onPress={() => link(user.linkedinUrl)} activeOpacity={0.7} className="flex-row items-center px-4 py-3.5"><FontAwesome name="linkedin-square" size={22} color="#60a5fa" /><View className="ml-3 flex-1"><Text className="font-semibold text-foreground dark:text-foreground-dark">LinkedIn</Text><Text className="mt-0.5 text-xs text-muted dark:text-muted-dark" numberOfLines={1}>{host(user.linkedinUrl)}</Text></View><MaterialIcons name="open-in-new" size={18} color="#94a3b8" /></TouchableOpacity>}</View></View>}
    <View className="mb-7"><Text className="mb-3 text-xs font-bold uppercase tracking-widest text-muted dark:text-muted-dark">Appearance</Text><View className="flex-row rounded-xl bg-slate-200 p-1 dark:bg-slate-800">{(['system', 'light', 'dark'] as ThemeMode[]).map((mode) => { const selected = themeMode === mode; return <Pressable key={mode} onPress={() => setThemeMode(mode)} className={selected ? 'flex-1 rounded-lg border border-border bg-surface py-2.5 dark:border-border-dark dark:bg-surface-dark' : 'flex-1 rounded-lg py-2.5'}><Text className={selected ? 'text-center text-xs font-semibold capitalize text-blue-600 dark:text-blue-400' : 'text-center text-xs font-semibold capitalize text-muted dark:text-muted-dark'}>{mode}</Text></Pressable>; })}</View></View>
    <TouchableOpacity onPress={onLogout} className="flex-row items-center justify-center rounded-xl border border-red-200 bg-red-50 py-3.5 dark:border-red-900 dark:bg-red-950" activeOpacity={0.7}><MaterialIcons name="logout" size={19} color="#ef4444" /><Text className="ml-2 font-semibold text-red-500">Log Out</Text></TouchableOpacity></ScrollView>
    <Modal visible={editing} animationType="slide" presentationStyle="pageSheet" onRequestClose={() => setEditing(false)}><SafeAreaView className="flex-1 bg-background dark:bg-background-dark"><View className="flex-row items-center justify-between border-b border-border px-5 py-4 dark:border-border-dark"><Text className="text-lg font-bold text-foreground dark:text-foreground-dark">Edit Profile</Text><TouchableOpacity onPress={() => setEditing(false)} className="p-1"><MaterialIcons name="close" size={24} color="#94a3b8" /></TouchableOpacity></View><ScrollView className="flex-1 px-5 pt-5" keyboardShouldPersistTaps="handled" contentContainerStyle={{ paddingBottom: 28 }}><Text className="mb-4 text-xs font-bold uppercase tracking-widest text-muted dark:text-muted-dark">Professional</Text>{field('Job title', 'jobTitle', 'Software Engineer')}{field('Bio', 'bio', 'A short professional bio', { multiline: true })}{field('Years of experience', 'yearsExperience', '2', { keyboardType: 'numeric' })}<Text className="mb-4 mt-3 text-xs font-bold uppercase tracking-widest text-muted dark:text-muted-dark">Skills & location</Text>{field('Skills', 'skills', 'React, TypeScript, Node.js')}{field('Location', 'location', 'City, Country')}<Text className="mb-4 mt-3 text-xs font-bold uppercase tracking-widest text-muted dark:text-muted-dark">Links</Text>{field('GitHub URL', 'githubUrl', 'https://github.com/username', { keyboardType: 'url' })}{field('LinkedIn URL', 'linkedinUrl', 'https://linkedin.com/in/username', { keyboardType: 'url' })}<TouchableOpacity onPress={save} disabled={updateProfile.isPending} className="mt-2 items-center rounded-xl bg-blue-600 py-3.5" activeOpacity={0.75}>{updateProfile.isPending ? <ActivityIndicator color="#fff" /> : <Text className="font-semibold text-white">Save changes</Text>}</TouchableOpacity></ScrollView></SafeAreaView></Modal></SafeAreaView>;
}
