ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GITHUB_PR_OPENED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GITHUB_PR_CLOSED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GITHUB_PR_REOPENED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'GITHUB_PR_REVIEW_REQUESTED';

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GITHUB_PR_OPENED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GITHUB_PR_CLOSED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GITHUB_PR_REOPENED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GITHUB_PR_REVIEW_REQUESTED';

ALTER TABLE "Project" ADD COLUMN "githubRepoFullName" TEXT;
CREATE UNIQUE INDEX "Project_githubRepoFullName_key" ON "Project"("githubRepoFullName");

ALTER TABLE "Activity" ALTER COLUMN "issueId" DROP NOT NULL;
ALTER TABLE "Activity" ADD COLUMN "projectId" TEXT;
ALTER TABLE "Activity" ALTER COLUMN "actorId" DROP NOT NULL;
ALTER TABLE "Activity" ADD CONSTRAINT "Activity_projectId_fkey"
  FOREIGN KEY ("projectId") REFERENCES "Project"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE INDEX "Activity_projectId_createdAt_id_idx" ON "Activity"("projectId", "createdAt", "id");
